workflows:
  android:
    name: Android build
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        GOOGLE_SERVICES_JSON: $GOOGLE_SERVICES_JSON
    scripts:
      - name: Decode google-services.json
        script: |
          echo $GOOGLE_SERVICES_JSON | base64 --decode > android/app/google-services.json
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
